USE `emicall_cc_man`;

/*1*/
#CM_CR_Version_v1.0-RC3 

call emicall_cc_man.func_handle_change('emicall_cc_man','seat_c_state_record','id','id','bigint(20) unsigned NOT NULL','DEFAULT 0 COMMENT \'对应cr记录表的id\''); 
/*3142*/

call emicall_cc_man.func_handle_column('emicall_cc_man','batch_call_task','add','task_duration','int(10) unsigned NOT NULL DEFAULT \'0\'','COMMENT \'任务执行时长\' after is_new');
/*3256*/

call emicall_cc_man.func_handle_index('emicall_cc_man','async_task','add','index','created_at','created_at');
/*3491*/

call emicall_cc_man.func_handle_index('emicall_cc_man','call_record','add','index','call_record_stat','stat_status');
call emicall_cc_man.func_handle_index('emicall_cc_man','call_record','add','index','encrypted_outline_number','encrypted_outline_number');
/*3578*/

call emicall_cc_man.func_handle_column('emicall_cc_man','terminal_number','add','is_bind_seat','tinyint(4) unsigned NOT NULL DEFAULT \'0\'','COMMENT \'是否绑定坐席 0-否 1-是\'');
call emicall_cc_man.func_handle_column('emicall_cc_man','terminal_number','add','is_bind_imei','tinyint(4) unsigned NOT NULL DEFAULT \'0\'','COMMENT \'是否绑定imei 0-否 1-是\'');
call emicall_cc_man.func_handle_index('emicall_cc_man','terminal_number','add','index','is_bind_seat','is_bind_seat');
call emicall_cc_man.func_handle_column('emicall_cc_man','sip_number','add','is_bind_seat','tinyint(4) unsigned NOT NULL DEFAULT \'0\'','COMMENT \'是否绑定坐席 0-否 1-是\'');
call emicall_cc_man.func_handle_index('emicall_cc_man','sip_number','add','index','is_bind_seat','is_bind_seat');
/*3871*/

call emicall_cc_man.func_handle_column('emicall_cc_man','call_detail','add','seat_ring_duration','int unsigned NOT NULL DEFAULT \'0\'','COMMENT \'坐席振铃时长(秒)\' AFTER cm_fail_reason');
call emicall_cc_man.func_handle_column('emicall_cc_man','call_detail','add','customer_ring_duration','int unsigned NOT NULL DEFAULT \'0\'','COMMENT \'客户振铃时长(秒)\' AFTER cm_fail_reason');
/*3902*/

call emicall_cc_man.func_handle_column('emicall_cc_man','batch_call_task','add','avg_ring_time','FLOAT NOT NULL DEFAULT \'0\'','COMMENT \'平均振铃时长\'');
call emicall_cc_man.func_handle_column('emicall_cc_man','batch_call_task_job','add','status','tinyint(2) NOT NULL DEFAULT \'0\'','COMMENT \'0-未开始 1-进行中 2-暂停中 3-已完成 4-已结束\'');
call emicall_cc_man.func_handle_column('emicall_cc_man','batch_call_task_job','add','call_progress','decimal(10,4) NOT NULL DEFAULT \'0.0000\'','COMMENT \'外呼进度\'');
call emicall_cc_man.func_handle_column('emicall_cc_man','batch_call_task_job','add','finished_customer_num','int(10) unsigned NOT NULL DEFAULT \'0\'','COMMENT \'已完成号码数\'');
call emicall_cc_man.func_handle_column('emicall_cc_man','batch_call_task_job','add','customer_pickup_rate','decimal(10,4) NOT NULL DEFAULT \'0.0000\'','COMMENT \'客户接通率\'');
call emicall_cc_man.func_handle_column('emicall_cc_man','batch_call_task_job','add','seat_pickup_rate','decimal(10,4) NOT NULL DEFAULT \'0.0000\'','COMMENT \'坐席接通率\'');
call emicall_cc_man.func_handle_column('emicall_cc_man','batch_call_task_job','add','queue_quit_rate','decimal(10,4) NOT NULL DEFAULT \'0.0000\'','COMMENT \'排队放弃率\'');
call emicall_cc_man.func_handle_column('emicall_cc_man','batch_call_task_job','add','customer_pickup_num','int(10) unsigned NOT NULL DEFAULT \'0\'','COMMENT \'客户接起数\'');
call emicall_cc_man.func_handle_column('emicall_cc_man','batch_call_task_job','add','queue_quit_num','int(10) unsigned NOT NULL DEFAULT \'0\'','COMMENT \'排队放弃数\'');
call emicall_cc_man.func_handle_column('emicall_cc_man','batch_call_task_job','add','seat_pickup_num','int(10) unsigned NOT NULL DEFAULT \'0\'','COMMENT \'坐席接起数\'');
call emicall_cc_man.func_handle_column('emicall_cc_man','batch_call_task_job','add','avg_ring_time','FLOAT NOT NULL DEFAULT \'0\'','COMMENT \'平均振铃时长\'');
call emicall_cc_man.func_handle_column('emicall_cc_man','batch_call_stat_seat','add','seat_number','varchar(63) COLLATE utf8mb4_unicode_ci DEFAULT NULL','COMMENT \'坐席分机号\'');
call emicall_cc_man.func_handle_column('emicall_cc_man','batch_call_stat_seat','add','seat_work_number','varchar(63) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT \'\'','COMMENT \'坐席工号\'');
call emicall_cc_man.func_handle_column('emicall_cc_man','batch_call_stat_seat','add','seat_call_rate','float NOT NULL DEFAULT \'0\'','COMMENT \'呼入接听率\'');
call emicall_cc_man.func_handle_column('emicall_cc_man','batch_call_stat_seat','add','ring_abort','int(11) unsigned NOT NULL DEFAULT \'0\'','COMMENT \'振铃放弃数\'');
call emicall_cc_man.func_handle_column('emicall_cc_man','batch_call_stat_seat','add','avg_ring_time','float NOT NULL DEFAULT \'0\'','COMMENT \'平均振铃时长\'');

CREATE TABLE IF NOT EXISTS batch_call_statistic_result (id bigint(20) unsigned NOT NULL AUTO_INCREMENT,seid bigint(20) unsigned NOT NULL DEFAULT '0' COMMENT '超级企业ID',ccgeid bigint(20) unsigned NOT NULL DEFAULT '0' COMMENT '企业ID',task_id bigint(20) unsigned NOT NULL DEFAULT '0' COMMENT '批量重呼任务ID',job_id bigint(20) unsigned NOT NULL DEFAULT '0' COMMENT '批量重呼批次ID',signed_count bigint(20) unsigned NOT NULL DEFAULT '0' COMMENT '标记数',result_id bigint(20) NOT NULL COMMENT '结果选项ID',result_name varchar(63) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '' COMMENT '结果选项名称',parent_result_id bigint(20) DEFAULT '0' COMMENT '父级结果选项ID',parent_result_name varchar(63) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '' COMMENT '父级结果选项名称',created_at int(10) NOT NULL,updated_at int(10) NOT NULL,PRIMARY KEY (id,seid,ccgeid),UNIQUE KEY task_job_result (seid,ccgeid,task_id,job_id,result_id,parent_result_id),KEY task_job_id (task_id,job_id),KEY result_id (result_id),KEY parent_result_id (parent_result_id),KEY created_at (created_at)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='批量外呼话后处理统计表' PARTITION BY KEY (seid,ccgeid) PARTITIONS 128;

CREATE TABLE IF NOT EXISTS batch_call_statistic_customer_call (id bigint(20) unsigned NOT NULL AUTO_INCREMENT,seid bigint(20) unsigned NOT NULL DEFAULT '0' COMMENT '超级企业ID',ccgeid bigint(20) unsigned NOT NULL DEFAULT '0' COMMENT '企业ID',task_id bigint(20) unsigned NOT NULL DEFAULT '0' COMMENT '批量重呼任务ID',job_id bigint(20) unsigned NOT NULL DEFAULT '0' COMMENT '批量重呼批次ID',signed_count bigint(20) unsigned NOT NULL DEFAULT '0' COMMENT '标记数',result_id bigint(20) NOT NULL COMMENT '结果选项ID',result_name varchar(63) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '' COMMENT '结果选项名称',parent_result_id bigint(20) DEFAULT '0' COMMENT '父级结果选项ID',parent_result_name varchar(63) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '' COMMENT '父级结果选项名称',created_at int(10) NOT NULL,updated_at int(10) NOT NULL,PRIMARY KEY (id,seid,ccgeid),UNIQUE KEY task_job_result (seid,ccgeid,task_id,job_id,result_id,parent_result_id),KEY task_job_id (task_id,job_id),KEY result_id (result_id),KEY parent_result_id (parent_result_id),KEY created_at (created_at)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='批量外呼客户通话统计表' PARTITION BY KEY (seid,ccgeid) PARTITIONS 128;
/*3913*/

update permission set icon='icon1-huajiguanli' where id=1800;
update permission set icon='icon1-heibaimingdan' where id=1900;
update permission set icon='icon1-peizhizhongxin' where id=9000;

call emicall_cc_man.func_handle_column('emicall_cc_man','call_detail','add','group_name','varchar(50) NOT NULL DEFAULT \'\'','COMMENT \'技能组名称\' AFTER seat_ring_duration');
call emicall_cc_man.func_handle_column('emicall_cc_man','call_detail','add','seat_work_number','varchar(63) NOT NULL DEFAULT \'\'','COMMENT \'工号\' AFTER seat_ring_duration');
call emicall_cc_man.func_handle_column('emicall_cc_man','call_detail','add','seat_number','varchar(63) NOT NULL DEFAULT \'\'','COMMENT \'分机号码\' AFTER seat_ring_duration');
call emicall_cc_man.func_handle_column('emicall_cc_man','call_detail','add','seat_displayname','varchar(127) NOT NULL DEFAULT \'\'','COMMENT \'坐席名称\' AFTER seat_ring_duration');
/*4018*/

call emicall_cc_man.func_handle_column('emicall_cc_man','batch_call_task','add','target','varchar(20) DEFAULT NULL','COMMENT \'seat 坐席、group 技能组\'');
call emicall_cc_man.func_handle_column('emicall_cc_man','batch_call_task_job','add','target','varchar(20) DEFAULT NULL','COMMENT \'seat 坐席、group 技能组\'');
call emicall_cc_man.func_handle_change('emicall_cc_man','call_detail','group_name','gid_name','varchar(50) NOT NULL DEFAULT \'\'','COMMENT \'技能组名称\' after gid');
call emicall_cc_man.func_handle_change('emicall_cc_man','call_detail','seat_work_number','work_number','varchar(63) NOT NULL DEFAULT \'\'','COMMENT \'工号\' after number');
call emicall_cc_man.func_handle_change('emicall_cc_man','call_detail','seat_displayname','display_name','varchar(127) NOT NULL DEFAULT \'\'','COMMENT \'坐席名称\' after number');
call emicall_cc_man.func_handle_column('emicall_cc_man','call_detail','drop','seat_number','varchar(63)','');

alter table call_record remove partitioning; call emicall_cc_man.func_handle_index('emicall_cc_man','call_record','add','unique index','s_c_cc_number','seid,ccgeid,cc_number'); call emicall_cc_man.func_handle_index('emicall_cc_man','call_record','drop','index','cc_number','seid,cc_number'); call emicall_cc_man.func_handle_index('emicall_cc_man','call_record','add','index','s_c_initiate_time','seid,ccgeid,initiate_time'); call emicall_cc_man.func_handle_index('emicall_cc_man','call_record','drop','index','initiate_time','initiate_time'); call emicall_cc_man.func_handle_index('emicall_cc_man','call_record','drop','index','duration','duration'); call emicall_cc_man.func_handle_index('emicall_cc_man','call_record','drop','index','ccgeid','ccgeid'); call emicall_cc_man.func_handle_index('emicall_cc_man','call_record','drop','index','encrypted_outline_number','encrypted_outline_number'); call emicall_cc_man.func_handle_index('emicall_cc_man','call_record','add','index','s_c_outline_number','seid,ccgeid,outline_number'); call emicall_cc_man.func_handle_index('emicall_cc_man','call_record','drop','index','outline_number','outline_number'); call emicall_cc_man.func_handle_change('emicall_cc_man','call_record','id','id','bigint(20) unsigned','default 0'); alter table call_record drop primary key; alter table call_record add PRIMARY KEY (id,seid,ccgeid); call emicall_cc_man.func_handle_change('emicall_cc_man','call_record','id','id','bigint(20) unsigned NOT NULL AUTO_INCREMENT','COMMENT \'自增长id\''); alter table call_record  partition BY KEY (seid,ccgeid) PARTITIONS 128;

alter table call_record_per_group_seat remove partitioning; call emicall_cc_man.func_handle_index('emicall_cc_man','call_record_per_group_seat','add','index','s_c_initiate_time','seid,ccgeid,initiate_time'); call emicall_cc_man.func_handle_index('emicall_cc_man','call_record_per_group_seat','drop','index','initiate_time','initiate_time'); call emicall_cc_man.func_handle_index('emicall_cc_man','call_record_per_group_seat','drop','index','duration','duration'); call emicall_cc_man.func_handle_index('emicall_cc_man','call_record_per_group_seat','drop','index','ccgeid','ccgeid'); call emicall_cc_man.func_handle_index('emicall_cc_man','call_record_per_group_seat','drop','index','cc_number','cc_number'); call emicall_cc_man.func_handle_index('emicall_cc_man','call_record_per_group_seat','add','index','s_c_outline_number','seid,ccgeid,outline_number'); call emicall_cc_man.func_handle_index('emicall_cc_man','call_record_per_group_seat','drop','index','outline_number','outline_number'); call emicall_cc_man.func_handle_change('emicall_cc_man','call_record_per_group_seat','id','id','bigint(20) unsigned','default 0'); alter table call_record_per_group_seat drop primary key; alter table call_record_per_group_seat add PRIMARY KEY (id,seid,ccgeid); call emicall_cc_man.func_handle_change('emicall_cc_man','call_record_per_group_seat','id','id','bigint(20) unsigned NOT NULL AUTO_INCREMENT','COMMENT \'自增长id\''); alter table call_record_per_group_seat  partition BY KEY (seid,ccgeid) PARTITIONS 128;

alter table call_record_per_group remove partitioning; call emicall_cc_man.func_handle_index('emicall_cc_man','call_record_per_group','add','index','s_c_initiate_time','seid,ccgeid,initiate_time'); call emicall_cc_man.func_handle_index('emicall_cc_man','call_record_per_group','drop','index','initiate_time','initiate_time'); call emicall_cc_man.func_handle_index('emicall_cc_man','call_record_per_group','drop','index','duration','duration'); call emicall_cc_man.func_handle_index('emicall_cc_man','call_record_per_group','drop','index','ccgeid','ccgeid'); call emicall_cc_man.func_handle_index('emicall_cc_man','call_record_per_group','drop','index','cc_number','cc_number'); call emicall_cc_man.func_handle_index('emicall_cc_man','call_record_per_group','add','index','s_c_outline_number','seid,ccgeid,outline_number'); call emicall_cc_man.func_handle_index('emicall_cc_man','call_record_per_group','drop','index','outline_number','outline_number'); call emicall_cc_man.func_handle_change('emicall_cc_man','call_record_per_group','id','id','bigint(20) unsigned','default 0'); alter table call_record_per_group drop primary key; alter table call_record_per_group add PRIMARY KEY (id,seid,ccgeid); call emicall_cc_man.func_handle_change('emicall_cc_man','call_record_per_group','id','id','bigint(20) unsigned NOT NULL AUTO_INCREMENT','COMMENT \'自增长id\''); alter table call_record_per_group  partition BY KEY (seid,ccgeid) PARTITIONS 128;

alter table call_record_per_seat remove partitioning; call emicall_cc_man.func_handle_index('emicall_cc_man','call_record_per_seat','add','index','s_c_initiate_time','seid,ccgeid,initiate_time'); call emicall_cc_man.func_handle_index('emicall_cc_man','call_record_per_seat','drop','index','initiate_time','initiate_time'); call emicall_cc_man.func_handle_index('emicall_cc_man','call_record_per_seat','drop','index','duration','duration'); call emicall_cc_man.func_handle_index('emicall_cc_man','call_record_per_seat','drop','index','ccgeid','ccgeid'); call emicall_cc_man.func_handle_index('emicall_cc_man','call_record_per_seat','drop','index','cc_number','cc_number'); call emicall_cc_man.func_handle_index('emicall_cc_man','call_record_per_seat','add','index','s_c_outline_number','seid,ccgeid,outline_number'); call emicall_cc_man.func_handle_index('emicall_cc_man','call_record_per_seat','drop','index','outline_number','outline_number'); call emicall_cc_man.func_handle_change('emicall_cc_man','call_record_per_seat','id','id','bigint(20) unsigned','default 0'); alter table call_record_per_seat drop primary key; alter table call_record_per_seat add PRIMARY KEY (id,seid,ccgeid); call emicall_cc_man.func_handle_change('emicall_cc_man','call_record_per_seat','id','id','bigint(20) unsigned NOT NULL AUTO_INCREMENT','COMMENT \'自增长id\''); alter table call_record_per_seat  partition BY KEY (seid,ccgeid) PARTITIONS 128;

call emicall_cc_man.func_handle_index('emicall_cc_man','ivr_flow_variable','drop','index','ivr_enterprise_version','ccgeid'); call emicall_cc_man.func_handle_index('emicall_cc_man','ivr_flow_variable','add','index','ivr_enterprise_version','seid,ccgeid'); call emicall_cc_man.func_handle_change('emicall_cc_man','ivr_flow_variable','id','id','bigint(20) unsigned','default 0'); alter table ivr_flow_variable drop primary key; alter table ivr_flow_variable add PRIMARY KEY (id); call emicall_cc_man.func_handle_change('emicall_cc_man','ivr_flow_variable','id','id','bigint(20) unsigned NOT NULL AUTO_INCREMENT','COMMENT \'自增长id\'');

call emicall_cc_man.func_handle_index('emicall_cc_man','ivr_node_set_variable','drop','index','ivr_enterprise_version','ccgeid'); call emicall_cc_man.func_handle_index('emicall_cc_man','ivr_node_set_variable','add','index','ivr_enterprise_version','seid,ccgeid');call emicall_cc_man.func_handle_change('emicall_cc_man','ivr_node_set_variable','id','id','bigint(20) unsigned','default 0'); alter table ivr_node_set_variable drop primary key; alter table ivr_node_set_variable add PRIMARY KEY (id); call emicall_cc_man.func_handle_change('emicall_cc_man','ivr_node_set_variable','id','id','bigint(20) unsigned NOT NULL AUTO_INCREMENT','COMMENT \'自增长id\'');

alter table statistics_of_ep_call remove partitioning; call emicall_cc_man.func_handle_change('emicall_cc_man','statistics_of_ep_call','id','id','bigint(20) unsigned','default 0'); alter table statistics_of_ep_call drop primary key; alter table statistics_of_ep_call add PRIMARY KEY (id,seid,ccgeid); call emicall_cc_man.func_handle_change('emicall_cc_man','statistics_of_ep_call','id','id','bigint(20) unsigned NOT NULL AUTO_INCREMENT','COMMENT \'自增长id\''); alter table statistics_of_ep_call  partition BY KEY (seid,ccgeid) PARTITIONS 128;

alter table statistics_of_group_call remove partitioning; call emicall_cc_man.func_handle_change('emicall_cc_man','statistics_of_group_call','id','id','bigint(20) unsigned','default 0'); alter table statistics_of_group_call drop primary key; alter table statistics_of_group_call add PRIMARY KEY (id,seid,ccgeid); call emicall_cc_man.func_handle_change('emicall_cc_man','statistics_of_group_call','id','id','bigint(20) unsigned NOT NULL AUTO_INCREMENT','COMMENT \'自增长id\''); alter table statistics_of_group_call  partition BY KEY (seid,ccgeid) PARTITIONS 128;

alter table statistics_of_seat_call remove partitioning; call emicall_cc_man.func_handle_change('emicall_cc_man','statistics_of_seat_call','id','id','bigint(20) unsigned','default 0'); alter table statistics_of_seat_call drop primary key; alter table statistics_of_seat_call add PRIMARY KEY (id,seid,ccgeid); call emicall_cc_man.func_handle_change('emicall_cc_man','statistics_of_seat_call','id','id','bigint(20) unsigned NOT NULL AUTO_INCREMENT','COMMENT \'自增长id\''); alter table statistics_of_seat_call  partition BY KEY (seid,ccgeid) PARTITIONS 128;

alter table statistics_of_seat_state_monitor remove partitioning; call emicall_cc_man.func_handle_change('emicall_cc_man','statistics_of_seat_state_monitor','id','id','bigint(20) unsigned','default 0'); alter table statistics_of_seat_state_monitor drop primary key; alter table statistics_of_seat_state_monitor add PRIMARY KEY (id,seid,ccgeid); call emicall_cc_man.func_handle_change('emicall_cc_man','statistics_of_seat_state_monitor','id','id','bigint(20) unsigned NOT NULL AUTO_INCREMENT','COMMENT \'自增长id\''); alter table statistics_of_seat_state_monitor  partition BY KEY (seid,ccgeid) PARTITIONS 128;

alter table statistics_of_seat_substate_monitor remove partitioning; call emicall_cc_man.func_handle_change('emicall_cc_man','statistics_of_seat_substate_monitor','id','id','bigint(20) unsigned','default 0'); alter table statistics_of_seat_substate_monitor drop primary key; alter table statistics_of_seat_substate_monitor add PRIMARY KEY (id,seid,ccgeid); call emicall_cc_man.func_handle_change('emicall_cc_man','statistics_of_seat_substate_monitor','id','id','bigint(20) unsigned NOT NULL AUTO_INCREMENT','COMMENT \'自增长id\''); alter table statistics_of_seat_substate_monitor  partition BY KEY (seid,ccgeid) PARTITIONS 128;

call emicall_cc_man.func_handle_index('emicall_cc_man','sync','add','index','seid_ccgeid','seid,ccgeid');
call emicall_cc_man.func_handle_index('emicall_cc_man','sync','drop','index','ccgeid','ccgeid');

call emicall_cc_man.func_handle_index('emicall_cc_man','terminal_number','drop','index','ccgeid','ccgeid');
call emicall_cc_man.func_handle_index('emicall_cc_man','terminal_tel','drop','index','ccgeid','ccgeid');

alter table seat remove partitioning; call emicall_cc_man.func_handle_index('emicall_cc_man','seat','add','index','s_c_number','seid,ccgeid,number'); call emicall_cc_man.func_handle_index('emicall_cc_man','seat','drop','index','number','number'); call emicall_cc_man.func_handle_index('emicall_cc_man','seat','drop','index','seid','seid'); call emicall_cc_man.func_handle_index('emicall_cc_man','seat','add','index','s_c_mobile','seid,ccgeid,mobile'); call emicall_cc_man.func_handle_index('emicall_cc_man','seat','drop','index','mobile','mobile'); call emicall_cc_man.func_handle_change('emicall_cc_man','seat','id','id','bigint(20) unsigned','default 0'); alter table seat drop primary key; alter table seat add PRIMARY KEY (id,seid); call emicall_cc_man.func_handle_change('emicall_cc_man','seat','id','id','bigint(20) unsigned NOT NULL AUTO_INCREMENT','COMMENT \'自增长用户id:uid\''); alter table seat  partition BY HASH (seid) PARTITIONS 128;

alter table seat_c_state_record remove partitioning; call emicall_cc_man.func_handle_change('emicall_cc_man','seat_c_state_record','id','id','bigint(20) unsigned','default 0'); alter table seat_c_state_record drop primary key; alter table seat_c_state_record add PRIMARY KEY (id,seid); call emicall_cc_man.func_handle_change('emicall_cc_man','seat_c_state_record','id','id','bigint(20) unsigned NOT NULL AUTO_INCREMENT','COMMENT \'对应cr记录表的id\''); alter table seat_c_state_record  partition BY HASH (seid) PARTITIONS 128;

alter table seat_realtime_state remove partitioning; call emicall_cc_man.func_handle_change('emicall_cc_man','seat_realtime_state','id','id','bigint(20) unsigned','default 0'); alter table seat_realtime_state drop primary key; alter table seat_realtime_state add PRIMARY KEY (id,seid); call emicall_cc_man.func_handle_change('emicall_cc_man','seat_realtime_state','id','id','bigint(20) unsigned NOT NULL AUTO_INCREMENT','COMMENT \'自增长id\''); alter table seat_realtime_state  partition BY HASH (seid) PARTITIONS 128;

alter table seat_setting remove partitioning; call emicall_cc_man.func_handle_change('emicall_cc_man','seat_setting','id','id','bigint(20) unsigned','default 0'); alter table seat_setting drop primary key; alter table seat_setting add PRIMARY KEY (id,seid); call emicall_cc_man.func_handle_change('emicall_cc_man','seat_setting','id','id','bigint(20) unsigned NOT NULL AUTO_INCREMENT','COMMENT \'自增长id\''); alter table seat_setting  partition BY HASH (seid) PARTITIONS 128;

alter table group_seat remove partitioning; call emicall_cc_man.func_handle_index('emicall_cc_man','group_seat','add','index','uid','uid'); call emicall_cc_man.func_handle_index('emicall_cc_man','group_seat','drop','index','ccgeid_uid','ccgeid'); call emicall_cc_man.func_handle_change('emicall_cc_man','group_seat','id','id','bigint(20) unsigned','default 0'); alter table group_seat drop primary key; alter table group_seat add PRIMARY KEY (id,seid); call emicall_cc_man.func_handle_change('emicall_cc_man','group_seat','id','id','bigint(20) unsigned NOT NULL AUTO_INCREMENT','COMMENT \'自增长id\''); alter table group_seat  partition BY HASH (seid) PARTITIONS 128;

alter table `group` remove partitioning; call emicall_cc_man.func_handle_index('emicall_cc_man','group','add','index','s_c_gid','seid,ccgeid,gid'); call emicall_cc_man.func_handle_index('emicall_cc_man','group','drop','index','ccgeid_gid','ccgeid'); call emicall_cc_man.func_handle_change('emicall_cc_man','group','id','id','bigint(20) unsigned','default 0'); alter table `group` drop primary key; alter table `group` add PRIMARY KEY (id,seid); call emicall_cc_man.func_handle_change('emicall_cc_man','group','id','id','bigint(20) unsigned NOT NULL AUTO_INCREMENT','COMMENT \'自增长id\''); alter table `group`  partition BY HASH (seid) PARTITIONS 128;

alter table group_setting remove partitioning; call emicall_cc_man.func_handle_change('emicall_cc_man','group_setting','id','id','bigint(20) unsigned','default 0'); alter table group_setting drop primary key; alter table group_setting add PRIMARY KEY (id,seid); call emicall_cc_man.func_handle_change('emicall_cc_man','group_setting','id','id','bigint(20) unsigned NOT NULL AUTO_INCREMENT','COMMENT \'自增长id\''); alter table group_setting  partition BY HASH (seid) PARTITIONS 128;
/*4064*/

CREATE TABLE IF NOT EXISTS group_realtime_state (id bigint(20) unsigned NOT NULL AUTO_INCREMENT,gid bigint(20) unsigned NOT NULL DEFAULT '0' COMMENT '技能组ID',seid bigint(20) unsigned NOT NULL DEFAULT '0' COMMENT '超级企业ID', ccgeid bigint(20) unsigned NOT NULL DEFAULT '0' COMMENT '企业ID', state_id bigint(20) unsigned NOT NULL DEFAULT '0' COMMENT '状态ID', state_name varchar(63) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '' COMMENT '状态名称', state_switch_time bigint(20) unsigned NOT NULL DEFAULT '0' COMMENT '状态上次变化时间', created_at bigint(20) unsigned NOT NULL DEFAULT '0', updated_at bigint(20) unsigned NOT NULL DEFAULT '0', PRIMARY KEY (id,seid,ccgeid), UNIQUE KEY seid (seid,ccgeid,gid), KEY state_id (state_id)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='技能组实时状态表' PARTITION BY KEY (seid,ccgeid) PARTITIONS 128;
/*4386*/

call emicall_cc_man.func_handle_column('emicall_cc_man','batch_call_task','add','uid_list','text NOT NULL','COMMENT \'uid列表\'');
call emicall_cc_man.func_handle_column('emicall_cc_man','batch_call_task','add','seat_refuse_num','int(10) unsigned NOT NULL DEFAULT \'0\'','COMMENT \'坐席流转数\'');
call emicall_cc_man.func_handle_column('emicall_cc_man','batch_call_task','add','seat_ring_num','int(10) unsigned NOT NULL DEFAULT \'0\'','COMMENT \'坐席振铃数\'');
call emicall_cc_man.func_handle_column('emicall_cc_man','batch_call_task','add','total_ring_time','int(10) unsigned NOT NULL DEFAULT \'0\'','COMMENT \'坐席振铃总时长\'');

call emicall_cc_man.func_handle_column('emicall_cc_man','batch_call_stat_seat','add','ring_no_answ_num','int(10) NOT NULL DEFAULT \'0\'','COMMENT \'坐席未接数-流转给别的坐席接听\' after seat_pickup_num');
call emicall_cc_man.func_handle_change('emicall_cc_man','batch_call_stat_seat','average_talk_time','average_talk_time','float NOT NULL DEFAULT \'0\'','COMMENT \'平均通话时长\'');
call emicall_cc_man.func_handle_change('emicall_cc_man','batch_call_stat_seat','seat_call_rate','seat_call_rate','decimal(10,4) NOT NULL DEFAULT \'0.0000\'','COMMENT \'呼入接听率\'');
call emicall_cc_man.func_handle_change('emicall_cc_man','batch_call_stat_seat','total_talk_time','total_talk_time','float NOT NULL DEFAULT \'0\'','COMMENT \'总通话时长\'');
call emicall_cc_man.func_handle_column('emicall_cc_man','batch_call_stat_seat','add','total_ring_time','float NOT NULL DEFAULT \'0\'','COMMENT \'总的振铃时长\' after ring_abort');
call emicall_cc_man.func_handle_column('emicall_cc_man','batch_call_stat_seat','add','total_ring_times','int(11) unsigned NOT NULL DEFAULT \'0\'','COMMENT \'总的振铃次数\' after ring_abort');

call emicall_cc_man.func_handle_column('emicall_cc_man','batch_call_stat_job','add','avg_ring_time','float NOT NULL DEFAULT \'0\'','COMMENT \'平均振铃时长\' after job_id');
call emicall_cc_man.func_handle_column('emicall_cc_man','batch_call_stat_job','add','queue_quit_rate','decimal(10,4) NOT NULL DEFAULT \'0.0000\'','COMMENT \'排队放弃率\' after job_id');
call emicall_cc_man.func_handle_column('emicall_cc_man','batch_call_stat_job','add','seat_pickup_rate','decimal(10,4) NOT NULL DEFAULT \'0.0000\'','COMMENT \'坐席接通率\' after job_id');
call emicall_cc_man.func_handle_column('emicall_cc_man','batch_call_stat_job','add','customer_pickup_rate','decimal(10,4) NOT NULL DEFAULT \'0.0000\'','COMMENT \'客户接通率\' after job_id');
call emicall_cc_man.func_handle_column('emicall_cc_man','batch_call_stat_job','add','call_progress','decimal(10,4) NOT NULL DEFAULT \'0.0000\'','COMMENT \'外呼进度\' after job_id');
call emicall_cc_man.func_handle_column('emicall_cc_man','batch_call_stat_job','add','status','tinyint(2) NOT NULL DEFAULT \'0\'','COMMENT \'0-未开始 1-进行中 2-暂停中 3-已完成 4-已结束\' after job_id');
call emicall_cc_man.func_handle_column('emicall_cc_man','batch_call_stat_job','add','queue_num','int(10) unsigned NOT NULL DEFAULT \'0\'','COMMENT \'排队总数\' after unfinish_customer_num');
call emicall_cc_man.func_handle_column('emicall_cc_man','batch_call_stat_job','add','seat_pickup_num','int(10) unsigned NOT NULL DEFAULT \'0\'','COMMENT \'坐席接起数\' after unfinish_customer_num');
call emicall_cc_man.func_handle_column('emicall_cc_man','batch_call_stat_job','add','customer_pickup_num','int(10) unsigned NOT NULL DEFAULT \'0\'','COMMENT \'客户接起数\' after unfinish_customer_num');
call emicall_cc_man.func_handle_column('emicall_cc_man','batch_call_stat_job','drop','success_call_num','int','');
call emicall_cc_man.func_handle_column('emicall_cc_man','batch_call_stat_job','drop','failed_call_num','int','');
/*4432*/

call emicall_cc_man.func_handle_change('emicall_cc_man','call_record_recording','id','id','bigint(20) unsigned','default 0'); alter table call_record_recording drop primary key; alter table call_record_recording add PRIMARY KEY (id,cc_number); call emicall_cc_man.func_handle_change('emicall_cc_man','call_record_recording','id','id','bigint(20) unsigned NOT NULL AUTO_INCREMENT','COMMENT \'自增长id\''); alter table call_record_recording  partition BY KEY (cc_number) PARTITIONS 128; 
/*4479*/
